import * as def from './default.json';
import * as hero from './hero.json';
import * as header from './header.json';
import * as footer from './footer.json';
import * as carousel from './carousel.json';
import * as aboutushome from './aboutushome.json';
import * as newsandevents from './newsandevents.json';
import * as productpreviews from './productpreviews.json';
import * as aboutrightpicture from './aboutrightpicture.json';
export { def as default, hero, header, footer, carousel, aboutushome, newsandevents, productpreviews, aboutrightpicture, };
